Добавляет интерфейсы для парсеров
Dan1elNeal/liquid-log pull request #2
Opened 2018-10-17 09:00 UTC by Dan1elNeal

@ykalemi
@d0k1
@etitov

2018-10-17 13:33 UTC, gallyamb requested changes

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +public class App {
Кажется, поехали стили

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +    private static int fiveMinutes = 5 * 60 * 1000;
`final`?

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +    private static int fiveMinutes = 5 * 60 * 1000;
`static` поля именуются UPPER_SNAKE_CASE

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +                parseLogFile(fileName, new SdngTimeParser(timeZone), new SdngDataParser());
А data parser и time parser не связаны? Т.е. не может ли data parser сам для себя создавать time parser?

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +            case "top":
Что будет, если создать еще один тип? Как сделать так, чтобы было легко расширять?

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/GcDataParser.java
> +    public void ParseLine(DataSet dataSet, String line) {
так в коде методы с маленькой или большой буквы именуются?

2018-10-17 13:33 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/IDataParser.java
> +    void ParseLine(DataSet data, String line);
Откуда уверенность, что все данные вмещаются в одну строку?

2018-10-21 18:56 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +public class App {
Буду к файлам, которые трогаю в рамках задачи применять автоформат (option + command + L на маке в  IntelliJ IDEA)
![image](https://user-images.githubusercontent.com/22240112/47270970-b5fa0800-d58c-11e8-8984-ac6e15b51502.png)
Код стайл, который он предлагает, для меня выглядит более приятным.

2018-10-21 18:58 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/GcDataParser.java
> +    public void ParseLine(DataSet dataSet, String line) {
С маленькой, поправил )

2018-10-21 19:08 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +public class App {
К сожалению или счастью, в существующих проектах никто не позволит тебе менять форматирование, потому что тебе оно кажется неприятным. Не думаю, что это уместно и здесь

2018-10-21 19:08 UTC, Gebon commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +            case "top":
Это, кстати, по заданию не требуется. Но подумать на будущее стоит

2018-10-21 19:10 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/IDataParser.java
> +    void ParseLine(DataSet data, String line);
Данные считываются построчно. Скармливаем каждую строчку из файла-лога в `IDataParser`, он достаёт из нее какие-то полезные данные для сохранения в БД.

2018-10-21 19:32 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +            case "top":
Добавится ещё один `case`.
Возможно, было бы удобно сделать map, в котором ключ - имя парсера, значение - функция, возвращающая `IDataParser`. Другое решение без `switch`'а или `if`'ов не могу придумать.

2018-10-21 19:36 UTC, Dan1elNeal commented
@ykalemi
@d0k1
@etitov
@Gebon 

Все, что пометил  реакцией 👍🏻 - поправил.

2018-10-21 19:49 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +public class App {
Спорить не буду, вернул обратно.
Подходил после пары к преподавателю посетовать на отсутствие определенного стиля кода в проекте, он же мне и посоветовал заюзать автоформат.

2018-10-21 19:53 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +public class App {
Пум
![image](https://user-images.githubusercontent.com/22240112/47271615-8c44df00-d594-11e8-9c1c-9815a09bd522.png)
Пум
![image](https://user-images.githubusercontent.com/22240112/47271634-b8606000-d594-11e8-9266-c69dd63d4762.png)

2018-10-22 04:53 UTC, ykalemi commented
Про автоформат - у нас ограничений нет. Но выносите это в отдельный коммит (лучше так делать всегда, а не только в этой практике), чтобы не усложнять жизнь проверяющим

2018-10-22 12:53 UTC, gallyamb approved these changes

2018-10-22 17:42 UTC, merged