Уменьшает потребление памяти при парсинге
Dan1elNeal/liquid-log pull request #3
Opened 2018-10-24 00:46 UTC by Dan1elNeal

@ykalemi
@d0k1
@etitov

2018-10-25 07:57 UTC, etitov commented
посмотрю

2018-10-25 17:13 UTC, ykalemi reviewed
В целом все ок, небольшое косметическое замечание

2018-10-25 17:13 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private static DataSetProvider DATA_SET_PROVIDER = null;
а нужен вам этот объект как статическое поле класса? В parseLogFile можно передать как аргумент

2018-10-28 16:13 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private static DataSetProvider DATA_SET_PROVIDER = null;
Поправил

2018-10-28 16:14 UTC, Dan1elNeal commented
@ykalemi
@d0k1
@etitov

2018-10-29 07:53 UTC, ykalemi approved these changes

2018-10-29 09:13 UTC, d0k1 requested changes

2018-10-29 09:13 UTC, d0k1 commented on src/test/java/ru/naumen/sd40/log/parser/DataSetProviderTest.java
> +        Assert.assertEquals(dataSet.getClass(), DataSet.class);
Поясните пожалуйста в чем суть теста?
если я правильно понял тест проверят что Java действительно статически типизирована, в переменной типа DataSet находится на самом деле экземпляр класса DataSet

2018-10-29 09:13 UTC, d0k1 commented on src/test/java/ru/naumen/sd40/log/parser/DataSetProviderTest.java
> +        Assert.assertEquals(firstDataSet, secondDataSet);
а здесь что с чем и зачем сравнивается?

2018-10-30 20:44 UTC, Dan1elNeal commented on src/test/java/ru/naumen/sd40/log/parser/DataSetProviderTest.java
> +        Assert.assertEquals(firstDataSet, secondDataSet);
Здесь проверяем, что при вызове с одинаковым ключом возвращается один тот же объект.

В реализации нашего парсера в качестве ключа используется время. Сохранять логи для одного и того же времени нужно в один DataSet.

2018-10-30 20:45 UTC, Dan1elNeal commented on src/test/java/ru/naumen/sd40/log/parser/DataSetProviderTest.java
> +        Assert.assertEquals(dataSet.getClass(), DataSet.class);
Да, все так. Перестарался )

2018-10-30 20:47 UTC, Dan1elNeal commented
@d0k1

2018-10-31 07:12 UTC, Dan1elNeal commented
Я вмержу, чтобы не бранчеваться от этой ветки для следующего задания

2018-10-31 07:12 UTC, merged

2018-10-31 07:15 UTC, d0k1 reviewed
принято