Делает каждый парсер бином
Dan1elNeal/liquid-log pull request #6
Opened 2018-11-14 12:32 UTC by Dan1elNeal

Первый пункт из домашки(хранить в `DataSet` только классы данных) сделал в прошлом пулл реквесте.

@ykalemi
@d0k1
@etitov

2018-11-14 13:56 UTC, ykalemi requested changes

2018-11-14 13:56 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/ErrorParser.java
>      private Pattern warnRegEx = Pattern.compile("^\\d+ \\[.+?\\] \\(.+?\\) WARN");
к этому коммиту не относится (можно сделать потом отдельным коммитом). Пройдитесь по всем парсерам: все эти паттерны - это константы, пусть они и будут константами, а не просто полями объекта.

2018-11-14 13:56 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private SdngTimeParser sdngTimeParser;
Если я правильно понял, то у вас была следующая идея - вы хотите, чтобы при каждом новом парсинге у вас здесь был новый экземпляр TimeParser (ведь для этого они помечены prototype). Предлагаю вам проверить - получилось ли это. (сделайте логирование в конструкторе, например)

2018-11-14 13:56 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private TopTimeParser topTimeParser;
Пугает такое количество аргументов. (на лекции ещё обсуждали, что внедрение через конструктор - предпочтительнее). Но ок, в следующих задачах это всё равно должно быть решено.

Тут дело в том, что ваш код на данный момент не очень хорошо расширяется. Если нужно добавить ещё один парсер - то добавиться сразу 2 поля в данный класс. И так до бесконечности.

2018-11-14 13:56 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private IDataParser dataParser;
Вот это неправильно. Ваш парсер - синглтон. Но у него внезапно появилось состояние. И оно зависит от текущего файла, который он парсит. Если запустить два процесса одновременно, то результат будет непредсказуемый.

Причём, не ясно, зачем вам надо хранить это состояние?

2018-11-14 13:56 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private SdngTimeParser sdngTimeParser;
В принципе, пока что не было задачи сделать и TimeParser-ы спринг-бинами. Но предлагаю всё же разобраться в проблеме.

2018-11-25 20:52 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private SdngTimeParser sdngTimeParser;
Да, тут я ошибся. Создается один экземпляр TimeParser'a.
Для создания нового экземпляра нужно воспользоваться конфигурацией.

2018-11-25 21:04 UTC, Dan1elNeal commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    private IDataParser dataParser;
Вы правы. Могут возникнуть проблемы, если в короткий промежуток времени прилетят два запроса, требующих разные парсеры.
Поправил.

2018-11-25 21:05 UTC, Dan1elNeal commented
@ykalemi
@d0k1
@etitov

Прошу прощения за то,  что долго не вносил правки.
Надеюсь задача зачтется хоть в каком-то виде.

2018-11-26 08:23 UTC, ykalemi commented
Да, ок. Теперь только TimeParser-ы больше не используются как spring bean-ы. Надо с них аннотации тогда снять?

2018-11-26 08:48 UTC, Dan1elNeal commented
@ykalemi

Упс, забыл убрать.
Поправил.

2018-11-26 08:49 UTC, ykalemi approved these changes
Надеюсь, что вы это запускали и проверяли :-)

2018-11-26 08:50 UTC, Dan1elNeal commented
Запускал и проверял )

2018-11-26 08:51 UTC, merged